In [2]:
import numpy as np

In [15]:
a = np.array([[1, 0],
              [1, 2]])

print("Original 2-d array:")
print(a)

det = np.linalg.det(a)
print("Determinant of the said 2-D array:")
print(det)

Original 2-d array:
[[1 0]
 [1 2]]
Determinant of the said 2-D array:
2.0


In [14]:
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]

print("Original matrices:")
print("p =", p)
print("q =", q)

result1 = np.dot(p, q)
print("Result of the matrix multiplication:")
print(result1, "\n")

Original matrices:
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
Result of the matrix multiplication:
[[1 2]
 [3 4]] 



In [13]:
import numpy as np

array1 = np.array([6, 7, 8])
array2 = np.array([[1, 2, 3],
                   [6, 7, 8]])

print("Data of array1 is:", array1.data)
print("Data of array2 is:", array2.data)


Data of array1 is: <memory at 0x000002151824DB40>
Data of array2 is: <memory at 0x0000021536DABE00>


In [12]:
import numpy as np

array1 = np.array([6, 7, 8, 10, 13])  # default int64
array2 = np.array([6, 7, 8, 10, 13], dtype=np.int32)  # 32-bit integers

print("itemsize of array1:", array1.itemsize)
print("itemsize of array2:", array2.itemsize)


itemsize of array1: 8
itemsize of array2: 4


In [11]:
import numpy as np

array1 = np.array([6, 7, 8])

print("dtype:", array1.dtype)


dtype: int64


In [10]:
import numpy as np

array1 = np.array([[1, 2, 3],
                   [6, 7, 8]])

print("shape:", array1.shape)


shape: (2, 3)


In [9]:
import numpy as np

array1 = np.array([[1, 2, 3],
                   [6, 7, 8]])

print("size:", array1.size)


size: 6


In [8]:
import numpy as np

array1 = np.array([[2, 4, 6],
                   [1, 3, 5]])

print("ndim:", array1.ndim)


ndim: 2


In [7]:
import numpy as np

int_array = np.array([1, 3, 5, 7])
float_array = int_array.astype('float')

print(int_array, int_array.dtype)
print(float_array, float_array.dtype)


[1 3 5 7] int64
[1. 3. 5. 7.] float64


In [6]:
import numpy as np

array1 = np.array([1, 3, 7], dtype='int8')
array2 = np.array([2, 4, 6], dtype='uint16')
array3 = np.array([1.2, 2.3, 3.4], dtype='float32')
array4 = np.array([1+2j, 2+3j, 3+4j], dtype='complex64')

print(array1, array1.dtype)
print(array2, array2.dtype)
print(array3, array3.dtype)
print(array4, array4.dtype)

[1 3 7] int8
[2 4 6] uint16
[1.2 2.3 3.4] float32
[1.+2.j 2.+3.j 3.+4.j] complex64


In [5]:
int_array = np.array([-3, -1, 0, 1])
float_array = np.array([0.1, 0.2, 0.3])
complex_array = np.array([1+2j, 2+3j, 3+4j])

print("int_array dtype:", int_array.dtype)      # prints int64
print("float_array dtype:", float_array.dtype)  # prints float64
print("complex_array dtype:", complex_array.dtype, "\n")  # prints complex128

int_array dtype: int64
float_array dtype: float64
complex_array dtype: complex128 



In [4]:
array1 = np.array([2, 4, 6])
print("Array1:", array1)
print("Data type of array1:", array1.dtype, "\n")

Array1: [2 4 6]
Data type of array1: int64 



In [3]:
arr = np.ones((2, 3))
print("numpy array:\n", arr)
print("Type:", type(arr), "\n")

numpy array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Type: <class 'numpy.ndarray'> 



In [20]:
import numpy as np
# Example 5: Create an array with zeros
array1 = np.zeros(4)
print(array1)

[0. 0. 0. 0.]


In [19]:
import numpy as np
# Example 4: Create a sequence of 5 values in range 0 to 3
arr = np.linspace(0, 3, 5)
print("A sequential array with 5 values between 0 and 3:\n", arr)

A sequential array with 5 values between 0 and 3:
 [0.   0.75 1.5  2.25 3.  ]


In [18]:
import numpy as np
# Example 3: Create a sequence of integers from 0 to 20 with steps of 3
arr = np.arange(0, 20, 3)
print("A sequential array with steps of 3:\n", arr)


A sequential array with steps of 3:
 [ 0  3  6  9 12 15 18]


In [17]:
import numpy as np
# Example 2: Create a 2D numpy array
arr2 = np.array([[10, 20, 30], [40, 50, 60]])
print("My 2D numpy array:\n", arr2)


My 2D numpy array:
 [[10 20 30]
 [40 50 60]]


In [16]:
import numpy as np
# Example 1: Creation of 1D array
arr1 = np.array([10, 20, 30])
print("My 1D array:\n", arr1)

My 1D array:
 [10 20 30]


In [15]:
import numpy as np
# Example 1: Creation of 1D array
arr1 = np.array([10, 20, 30])
print("My 1D array:\n", arr1)

My 1D array:
 [10 20 30]


In [14]:
array1 = np.random.rand(5)  
print("Array with 5 random numbers:", array1)

Array with 5 random numbers: [0.41578156 0.85264116 0.20725636 0.68365256 0.48879919]


In [13]:
# generate an array of 5 random numbers
array1 = np.random.rand(5)
print(array1)

[0.69664379 0.46858735 0.83940718 0.04578124 0.77988283]


In [12]:
array1 = np.arange(5)
print("Using np.arange(5):", array1)
array2 = np.arange(1, 9, 2)
print("Using np.arange(1, 9, 2):",array2)


Using np.arange(5): [0 1 2 3 4]
Using np.arange(1, 9, 2): [1 3 5 7]


In [9]:
arr3 = np.arange(0, 20, 3)
print("A sequential array with steps of 3:\n", arr3)

A sequential array with steps of 3:
 [ 0  3  6  9 12 15 18]


In [8]:
array1 = np.zeros(4)
print("Array with zeros:\n", array1)

Array with zeros:
 [0. 0. 0. 0.]


In [4]:
arr2 = np.array([[10, 20, 30], [40, 50, 60]])
print("My 2D numpy array:\n", arr2)

My 2D numpy array:
 [[10 20 30]
 [40 50 60]]


In [3]:
arr1 = np.array([10, 20, 30, 40, 50])
print("My 1D array:\n", arr1)

My 1D array:
 [10 20 30 40 50]


In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4 , 5 , 6 , 7 , 8])
print(a.ndim(4,2))
print(a.ndim(2,4))
print(a.ndim(4,2))
print(a.ndim(4,2))


1
1
1
1


In [6]:
import numpy as np
e = np.array(((((1)))))
f = np.array([[1], [2]])
g = np.array([1])
h = np.array((1))

print(e.ndim)
print(f.ndim)
print(g.ndim)
print(h.ndim)

0
2
1
0


In [4]:
d = np.array([[[[[1]]]]])
print(d)
print(d.ndim)


[[[[[1]]]]]
5


In [3]:
c = np.array([(1, 2), (3, 4)])
print(c)


[[1 2]
 [3 4]]


In [2]:
import numpy as np


print("\n---- NumPy PRACTICAL EXPERIMENT ----\n")

# ----------------------------------------------------------
# Example 1: Creation of 1D array (User Input)
# ----------------------------------------------------------
n = int(input("Enter number of elements for 1D array: "))
arr1 = np.array([int(input(f"Enter element {i+1}: ")) for i in range(n)])
print("My 1D array:\n", arr1, "\n")


---- NumPy PRACTICAL EXPERIMENT ----

My 1D array:
 [4 5 6 7] 

