In [1]:
import numpy as np

In [2]:
# (a) Create a 3x3 matrix with values ranging from 2 to 10
a = np.arange(2, 11).reshape(3, 3)
print("(a) 3x3 matrix with values 2 to 10:\n", a, "\n")

(a) 3x3 matrix with values 2 to 10:
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]] 



In [3]:
# (b) Reverse an array (first element becomes last)
b = np.array([1, 2, 3, 4, 5])
print("(b) Original array:", b)
print("Reversed array:", b[::-1], "\n")

(b) Original array: [1 2 3 4 5]
Reversed array: [5 4 3 2 1] 



In [4]:
# (c) Find common values between two arrays
c1 = np.array([1, 2, 3, 4, 5])
c2 = np.array([4, 5, 6, 7, 8])
print("(c) Common values between arrays:", np.intersect1d(c1, c2), "\n")

(c) Common values between arrays: [4 5] 



In [5]:
# (d) Repeat array elements
d = np.array([1, 2, 3])
print("(d) Repeat elements of array:", np.repeat(d, 3), "\n")

(d) Repeat elements of array: [1 1 1 2 2 2 3 3 3] 



In [6]:
# (e) Find the memory size of a NumPy array
e = np.array([10, 20, 30, 40, 50])
print("(e) Memory size of array (bytes):", e.size * e.itemsize, "\n")

(e) Memory size of array (bytes): 40 



In [7]:
# (f) Create an array of ones and zeros
f1 = np.ones((2, 3))
f2 = np.zeros((2, 3))
print("(f) Array of ones:\n", f1)
print("Array of zeros:\n", f2, "\n")

(f) Array of ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]] 



In [8]:
# (g) Find the 4th element of a specified array
g = np.array([10, 20, 30, 40, 50])
print("(g) The 4th element of the array:", g[3])

(g) The 4th element of the array: 40
