In [8]:
data = [1,2,3,4,5]
series = pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [6]:
C = np.dot(A,B)
C

array([[ 26,  13,  48],
       [ 65,  40, 117],
       [104,  67, 186]])

In [4]:
A + B

array([[ 6,  8, 10],
       [ 7,  7, 13],
       [12,  9, 18]])

In [3]:
import numpy as np

B = np.array([[5, 6, 7], [3, 2, 7], [5, 1, 9]])
print(B)


[[5 6 7]
 [3 2 7]
 [5 1 9]]


In [2]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
